use crate::sha::HashValue;
use mongodb::bson;

#[derive(Clone, Debug)]
pub enum GitInnerError {
    TimeError(String),
    InvalidSignatureType(String),
    ConversionError(String),
    InvalidTimestamp,
    InvalidSignature,
    InvalidTreeItem(String),
    InvalidSha1String,
    InvalidSha256String,
    LockError,
    InvalidUtf8,
    UnexpectedEof,
    InvalidData,
    NotSupportVersion,
    DecompressionError,
    InvalidObjectType,
    SqliteError(String),
    HashVersionError,
    Payload(String),
    IoError(String),
    BJSONERROR(bson::ser::Error),
    MongodbError(String),
    ObjectNotFound(HashValue),
    ObjectStoreError(String),
    UuidError,
    BaseObjectNotFound(Vec<u8>),
    InvalidDelta,
    MissingAuthor,
    MissingCommitter,
    MissingField(&'static str),
    InvalidHash,
    MissingBaseObject,
    DeltaInvalidInstruction,
    DeltaResultSizeMismatch,
    DeltaBaseSizeMismatch,
    InvalidZlib,
    UnsupportedOfsDelta,
    CommitParseError,
    TreeParseError,
    TagParseError,
}
